"""empty message

Revision ID: 8a588d571d71
Revises: 
Create Date: 2021-09-09 15:02:44.596710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a588d571d71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('local_governments', 'state_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=True)
    op.alter_column('local_governments', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'local_governments', 'states', ['state_id'], ['id'])
    op.drop_table_comment(
        'local_governments',
        existing_comment='Local governments in Nigeria.',
        schema=None
    )
    op.alter_column('states', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table_comment(
        'states',
        existing_comment='States in Nigeria.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'states',
        'States in Nigeria.',
        existing_comment=None,
        schema=None
    )
    op.alter_column('states', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_table_comment(
        'local_governments',
        'Local governments in Nigeria.',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'local_governments', type_='foreignkey')
    op.alter_column('local_governments', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('local_governments', 'state_id',
               existing_type=mysql.INTEGER(display_width=10),
               nullable=False)
    # ### end Alembic commands ###
