"""empty message

Revision ID: bddd4e5e965e
Revises: 8a588d571d71
Create Date: 2021-09-09 15:08:26.014550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddd4e5e965e'
down_revision = '8a588d571d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('ernest_message', sa.Text(), nullable=True))
    op.add_column('contact', sa.Column('show_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'show_message')
    op.drop_column('contact', 'ernest_message')
    # ### end Alembic commands ###
